version: '3.4'

services:
  grand.web:
    image: ${DOCKER_REGISTRY-}grandweb
    ulimits:
        nofile:
            soft: 1048576
            hard: 1048576
    build:
      context: .
      dockerfile: Grand.Web/Dockerfile
